### PR TITLE
add localization for valueGridColumn at NewEditPipe

### PR DESCRIPTION
**Pull request by DmitrySidorov**
Localization is not working for progress panel despite of existing translations #1285

### CODE REVIEW

**Comment by olga-jane** [comment]
+                    if (pipeTestResult.Operation.ResultType == PipeTestResultType.Boolean 
+                        && pipeTestResult.Operation.BoolExpected == true)
+                    { 
+                        e.DisplayText = Program.LanguageManager.GetString(StringResources.Yes); 
+                    }
+                    if (pipeTestResult.Operation.ResultType == PipeTestResultType.Boolean 
+                        && pipeTestResult.Operation.BoolExpected == false)
+                    { 
+                        e.DisplayText = Program.LanguageManager.GetString(StringResources.No); 
+                    }


+                    if (pipeTestResult.Operation.ResultType == PipeTestResultType.Boolean
+                        && tmpResult == true)
+                    {
+                        e.DisplayText = Program.LanguageManager.GetString(StringResources.Yes);
+                    }
+                    if (pipeTestResult.Operation.ResultType == PipeTestResultType.Boolean
+                        && tmpResult == false)
+                    {
+                        e.DisplayText = Program.LanguageManager.GetString(StringResources.No);
+                    }

I don't like these 2 blocks:

1) repeating code
2) boolean value twice checked

**Comment by olga-jane** [comment]
please, merge

**Comment by olga-jane** [comment]
Diameter choosing -> Select diameter
Construction pipes report -> Construction pipe report
Adding the inspection operation -> Add inspection operation

**Comment by DmitrySidorov** [comment]
ok, thanks

**Comment by olga-jane** [comment]
if (pipeTestResult.Operation.BoolExpected == true)
it is not necessary to compare with true

if (tmpResult == true)
it is not necessary to compare with true

other is OK

**Pull request merged**
