### PR TITLE
Inspector grade

### PR DESCRIPTION
**Pull request by demmy**
Настройка-инспекторы-сертификаты, нужен столбец уровень [27] #918 
**DB will change - need reinstall**

### CODE REVIEW

**Comment by olga-jane** [comment]
else if(c is DevExpress.XtraEditors.SimpleButton)

**Comment by olga-jane** [comment]
+commandManager.RefreshVisualState();
+IsModified = true;

I think sequence should be inverse

**Comment by olga-jane** [comment]
please merge

**Comment by demmy** [comment]
Merged

**Pull request merged**
