### PR TITLE
Sidorov export issues #PRISM-13 Fixed

### PR DESCRIPTION
**Pull request by DmitrySidorov**
PRISM-13 Export issues from client (additional information, appearance)

### CODE REVIEW

**Comment by olga-jane** [comment]
What will happen to already existing data in column? will they be OK?

ReleaseNoteNewEdit_DifferentTypeSizeInRailcarExtended isn't present both in code and in translations

**Comment by DmitrySidorov** [comment]
at serialization and deserialization we save data as DateTime, thus, no conflict whis already existing data in column.

**Comment by olga-jane** [comment]
UPD. please shift migration date (identifier)

**Comment by DmitrySidorov** [comment]
type conversion during migration need to discussion. there are no suitable solution yet

**Comment by DmitrySidorov** [comment]
testing: at migration date successfully converted to dateTime in existing db

**Pull request merged**
