### PR TITLE
Saving components with attached files in one transaction

### PR DESCRIPTION
**Pull request by serg7**
Refactor saving components with attached files in one transaction to avoid saving uncompletely data.

### CODE REVIEW

**Comment by olga-jane** [comment]
we need rollback in case files weren't written successfully

**Comment by olga-jane** [comment]
1) please, merge
2) please, add to standard Resources: both strings with the same id
ExternalFiles_NotCopied
ExternalFiles_NotCopied_Header
(and what in Resources, this is original text. StringResource.Description means the description in file with translations, for example
+        public static StringResource ExternalFiles_NotCopied_Header = new StringResource
+        {
+            Id = "ExternalFiles_NotCopied_Header",
+            Description = "Сообщение: Ошибка сохранения прикрепленных файлов"
+        };
is transformed later to (in Strings."culture".txt):
; Сообщение: Ошибка сохранения прикрепленных файлов
ExternalFiles_NotCopied_Header=
3) please edit the file
install/Lang/Translations/Strings.en-EN.txt 
and add english translations for both your strings, in the format, described above.

**Comment by olga-jane** [comment]
could we have these changes today?

**Comment by serg7** [comment]
ok. I will do it today

**Pull request closed without merging**
