### PR TITLE
Fix save setting

### PR DESCRIPTION
**Pull request by demmy**
Setting can not be saved #889
Setup of "Контрольные и ремонтные операции" at Pipeline isn't saved #856

### CODE REVIEW

**Comment by olga-jane** [comment]
please, merge

**Comment by demmy** [comment]
merged

**Comment by olga-jane** [comment]
+            //FIX: 'Prizm.Domain.Entity.Mill.Pipe' does not contain a definition for 'ToExport'
+            //this.Pipe.ToExport = false;
??

**Comment by demmy** [comment]
Pipe does not contain a definition for ToExport and code not compile.
 I'am temporaly comment this definition. Also i comment it in add toExport flag #893

**Comment by olga-jane** [comment]
merging artefacts remain in diffs 

+>>>>>>> origin/master
+                {
+                    if(Convert.ToString(inspectionView.GetRowCellValue(i, "Code")) == null || Convert.ToString(inspectionView.GetRowCellValue(i, "Name")) == null)
+                    {
+                        inspectionView.FocusedRowHandle = i;
+
+                        inspectionView_ValidateRow(
+                            inspectionView,
+                            new DevExpress.XtraGrid.Views.Base
+                                .ValidateRowEventArgs(i, inspectionView.GetDataRow(i)));
+                    }
+                }
+
+<<<<<<< HEAD
+                foreach(PipeTest t in viewModel.PipeTests)
+=======
+            foreach(PipeTest t in viewModel.PipeTests)
+            {
+                if(t.Code != null && t.Name != null)
+>>>>>>> origin/master

**Comment by demmy** [comment]
artefacts deleted

**Pull request merged**
