### PR TITLE
pogram run in single instance

### PR DESCRIPTION
**Pull request by demmy**
Запретить запуск более 1 копии программы #1597

### CODE REVIEW

**Comment by olga-jane** [comment]
please include all related to single-program-instance in PrizmApplicationXtraForm.cs in region block appropriately named
please also add xml comments to classes WinApi, SingleInstance, ProgramInfo with notes about their purpose

**Comment by olga-jane** [comment]
until WndProc is related to single instance functionality only,
please include it in #region SingleInstance

**Comment by demmy** [comment]
please review

**Comment by olga-jane** [comment]
please include WndProc in #region SingleInstance

**Comment by demmy** [comment]
region moved

**Pull request merged**
