### PR TITLE
Refactoring open RailcarNewEditXtraForm

### PR DESCRIPTION
**Pull request by ukrandruha**
Notification exception #1213
refactor ugly code on opening release note form (origin Release notes can collect pipes of other R.N. in process of editing #1029)

### CODE REVIEW

**Comment by olga-jane** [comment]
please add name and reference to issue into pull request description.

why OpenRailcarForm receives type of form, if this is form-type-specific method?

**Comment by ukrandruha** [comment]
RailcarForm receives type of form, because It will replace the old function - OpenChildForm

**Comment by olga-jane** [comment]
@ukrandruha 
please add name and reference to issue into pull request description.
please merge

**Comment by olga-jane** [comment]
one more problem: removed strings from Resources.resx

**Pull request merged**
